import { Platform, StyleSheet } from "react-native";
import Constants from "../constants";
import { isTablet, screenWidth } from "../platforms";
import { horizontal, moderate, vertical } from "../scales";

export default globalStyles = StyleSheet.create({
  button: {
    marginTop: 20,
    alignSelf: "stretch",
    height: 50,
    marginStart: horizontal(10),
    backgroundColor: '#F4E4B8',
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
  },

  textInput: {
    height: 50,
    borderWidth: 1,
    alignSelf: "stretch",
    marginVertical: 5,
    fontSize: 15,
    borderRadius: 8,
    borderColor: '#B4BAC8',
    backgroundColor: 'white',
    paddingStart: 10,
    fontFamily: Constants.FONT_HIRAGINO,
    color: 'black',
  },
  textButton: {
    color: 'white',
    fontWeight: "bold",
  },
  input: {
    width: screenWidth - horizontal(15) * 2 - 2,
    height: 54,
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
    padding: 15,
    color: "#3A4865",
    fontSize: 14,
    lineHeight: 16,
    borderColor: '#B4BAC8',
    borderWidth: 1,
  },
  roundButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#FD7A59",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#FD7A59",
        shadowOpacity: 0.5,
        elevation: 5,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 10 },
      },
      android: {
        elevation: 3,
      },
    }),
  },
  textConfirm: {
    height: 50,
    alignSelf: "stretch",
    marginVertical: 5,
    marginStart: horizontal(10),
    fontSize: 15,
    borderRadius: 8,
    backgroundColor: 'white',
    paddingStart: 10,
    fontFamily: Constants.FONT_HIRAGINO,
    color: 'black',
    paddingEnd: 10,
  },
  text_err: {
    alignSelf: "center",
    marginTop: 15,
    color: '#FD7A59',
    fontWeight: "bold",
  },
  mess_err: {
    color: '#FD7A59',
    fontWeight: "bold",
    fontSize: 12,
    marginStart: horizontal(10),
  },
  hiddenIcon: {
    position: "absolute",
    right: 18,
    alignSelf: "center",
  },
  containIconTab: {
    position: "absolute",
    top: 0,
    alignItems: "center",
    justifyContent: "space-between",
    height: "85%",
  },
  emptyTabbar: {
    width: 24,
    height: 4,
  },
  cmTwoButtonLeft: {
    width: "100%",
    backgroundColor: 'white',
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13.5,
    borderWidth: 1,
    borderColor: "#677187",
    height: 55,
  },
  textButtonLeft: {
    color: "#677187",
    fontSize: 14,
    fontWeight: "bold",
  },
  cmTwoButtonRight: {
    width: "100%",
    backgroundColor: "#FD7A59",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13.5,
    borderWidth: 1,
    borderColor: "#FD7A59",
    height: 55,
  },
  textButtonRight: {
    color: 'white',
    fontSize: 14,
    fontWeight: "bold",
  },
});
