export default {
  HOME: "HOME",
  AUTHOR_STACK: "AUTHOR_STACK",
  USER_STACK: "USER_STACK",
  IMAGE_DETAIL: "IMAGE_DETAIL",
  HOMESTACK: "HOMESTACK",
  PROFILESTACK: "PROFILESTACK",
  BOTTOM_TAB: "BOTTOM_TAB",
  HOME_TITLE_TAB: "Home",
  PROFILE_TITLE_TAB: "Profile",
  ACOUNT_INFOR: "ACOUNT_INFOR",
  TUTORIAL_SCREEN: "TUTORIAL_SCREEN",
};
