export default {
  HOME: "HOME",
  AUTHOR_STACK: "AUTHOR_STACK",
  USER_STACK: "USER_STACK",
  IMAGE_DETAIL: "IMAGE_DETAIL",
  HOMESTACK: "HOMESTACK",
  PROFILESTACK: "PROFILESTACK",
  BOTTOM_TAB: "BOTTOM_TAB",
  HOME_TITLE: "Home",
  PROFILE_TITLE: "Profile",
  ACOUNT_INFOR: "ACOUNT_INFOR",
};
